### ISSUE TITLE
[BUG] Fails to start in MacOS

### ISSUE THREAD

**Issue by diogox** [project-gauntlet/gauntlet#17]
Congrats on the project!

I'd like to give it a shot, but currently not able to start it:

```sh
dyld[80919]: Library not loaded: /opt/homebrew/opt/openssl@3/lib/libssl.3.dylib
  Referenced from: <800A73A5-8315-342F-8217-30AFABB93409> /Applications/Gauntlet.app/Contents/MacOS/Gauntlet
  Reason: tried: '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file), '/opt/homebrew/opt/openssl@3/lib/libssl.3.dylib' (no such file)
```

I installed it from the Release 9's .dmg file, but seems a dependency is missing.

**Comment by Exidex** [comment]
Thank you for trying it out and reporting the issue! 

It should be fixed in [08931e2](https://github.com/project-gauntlet/gauntlet/commit/08931e2c808a14b2445e0f955c0d7b56ac52be8f). I am planning to do the v10 release in 2 weeks or so. In the meantime you can workaround the issue by installing the openssl library manually: 
```
# macOS (Homebrew)
$ brew install openssl@3

# macOS (MacPorts)
$ sudo port install openssl

# macOS (pkgsrc)
$ sudo pkgin install openssl
```

**Comment by diogox** [comment]
Thanks!

I can confirm that building from the `main` branch doesn't raise an `openssl` issue.

And using `brew install openssl@3` fixes v9 :)

Feel free to close this issue 🙌 (I'll be raising a few more 😉)

**Comment by Exidex** [comment]
Lets leave it open until new version release in case somebody else faces the same issue

> I'll be raising a few more

Looking forward to it 🙂

**Comment by Exidex** [comment]
v10 is released. So closing this issue as well
