### ISSUE TITLE
Gauntlet shows up in MacOS Dock

### ISSUE THREAD

**Issue by diogox** [project-gauntlet/gauntlet#20]
Typically launchers like Raycast will hide the icon from the Dock:
![CleanShot 2024-10-04 at 22 42 55@2x](https://github.com/user-attachments/assets/c353321d-b1d5-4f2b-abf8-ecea81c52258)

And instead add a menu bar item:
![CleanShot 2024-10-04 at 22 46 23@2x](https://github.com/user-attachments/assets/c0834042-2e32-40c6-aa6f-67b4e1cc327b)

Not sure how hard that is to implement, but one for the roadmap :)

**Comment by Exidex** [comment]
I think this one also will be solved by using NSPanel instead of NSWindow. Same as https://github.com/project-gauntlet/gauntlet/issues/14. Unfortunately it will be some time until that is possible because of dependency hell described in https://github.com/project-gauntlet/gauntlet/issues/11.

**Comment by Exidex** [comment]
As for the menu item, it should already be implemented, does it not show?

**Comment by diogox** [comment]
> As for the menu item, it should already be implemented, does it not show?

You're right, I didn't spot it at first 😅

![CleanShot 2024-10-05 at 11 30 08@2x](https://github.com/user-attachments/assets/5c417631-15c9-4586-84b9-239fbdcecc59)

It actually stands out from the others due to the color scheme. Maybe a minor thing to improve later.

**Comment by Exidex** [comment]
Yes, I am not super happy with current logo and it will be reworked at some point including separate menu item icon

**Comment by Exidex** [comment]
Gauntlet v12 with fix is released. Closing this issue. New logo is still on my todo list
