### ISSUE TITLE
Icons do not render on Wayland

### ISSUE THREAD

**Issue by cswimr** [project-gauntlet/gauntlet#24]
On Wayland, icons do not render properly. I specify Wayland because I could not recreate this issue on X11.

![image](https://github.com/user-attachments/assets/55dff6ca-ab23-4794-b410-9161c4db68e0)

Where the icon is defined:
https://github.com/project-gauntlet/gauntlet/blob/ed29af658347e445f3f20be6d5ae0a86ab40e43b/bundled_plugins/gauntlet/src/calculator.tsx#L46

**Comment by schradert** [comment]
I can't reproduce this on Wayland built from `e32a024`

**Comment by Exidex** [comment]
Yes, this was fixed with migration to different layershell implementation. I will keep the ticket open until release

**Comment by Exidex** [comment]
Gauntlet v12 with fix is released. Closing this issue
