### ISSUE TITLE
Unable to Open Panel with Hotkey on Windows

### ISSUE THREAD

**Issue by fufuShih** [project-gauntlet/gauntlet#26]
## Description:
When using the `Alt + Space` hotkey on Windows, the panel does not show up. However, right-clicking on the widget and selecting the "Open" option successfully opens the panel. Even after changing to other hotkeys, the panel still cannot be triggered.

## Steps to Reproduce:
1. Install the application on Windows.
2. Attempt to open the panel using the `Alt + Space` hotkey.
3. The panel does not appear.
4. Right-click on the widget and select the "Open" option; the panel opens correctly.
5. Try changing to other hotkeys (e.g., `Ctrl + Alt + O`), but the panel still does not open with any hotkey.

## Expected Result:
The panel should display when pressing `Alt + Space` or any custom hotkey.

## Actual Result:
The panel does not display when using `Alt + Space` or any other custom hotkey.

## Env:
###OS: Windows
![image](https://github.com/user-attachments/assets/ae1b9768-9a92-43af-961c-2c3ebd6d96e7)

### App Version:
![image](https://github.com/user-attachments/assets/ce59cde6-3e18-49ba-b14a-dcdf010927bc)
![image](https://github.com/user-attachments/assets/8196d7c7-fc59-4eac-b14c-56f3fd651eac)

**Comment by Exidex** [comment]
Should be fixed in https://github.com/project-gauntlet/gauntlet/commit/508909cf7d5dff4ce6055e711a305aa466add4d8. Leaving this issue open until next release

**Comment by Exidex** [comment]
Gauntlet v11 with fix is released. Closing this issue

**Comment by fufuShih** [comment]
The current version is still v10 on Chocolatey.

![image](https://github.com/user-attachments/assets/011b0db7-cb7d-4835-90d2-d09f256142d9)

**Comment by Exidex** [comment]
@fufuShih
The approval process in Chocolatey is volunteer-based and is unfortunately very slow. I had a case where new version approval took more than 3 weeks. 

Fortunately, you should be able to upgrade by specifying new version explicitly: `choco upgrade gauntlet --version 11.0.0`. According to [documentation](https://docs.chocolatey.org/en-us/choco/commands/upgrade/) this should work, but I didn't have a chance to double check it

**Comment by fufuShih** [comment]
@Exidex 
Thanks for your response. After testing it just now, the command `choco Upgrade gauntlet --version 11.0.0` works perfectly.
